version: "3"
services:
  web:
    build:
      context: ./web
    environment:
      REACT_APP_SERVER_URL: "http://localhost:${SERVER_PORT}"
    ports:
      - "3000:3000"
    depends_on:
      - api
      - scripts
      - mysql

  api:
    build:
      context: ./api
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: ${SERVER_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "8080:8080"
    links:
      - ${DB_HOST}
    depends_on:
      - scripts
      - mysql
    volumes:
      - ${API_VOLUME}:/app

  scripts:
    build:
      context: ./scripts
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    links:
      - ${DB_HOST}
    depends_on:
      - ${DB_HOST}

  mysql:
    container_name: ${DB_HOST}
    image: mysql:latest
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql

volumes:
  api-data-prod:
  api-data-dev:
  mysql-data-prod:
  mysql-data-dev:
