version: "3"
services:
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    environment:
      REACT_APP_SERVER_URL: "http://localhost:8080"
    depends_on:
      - api
      - scripts
      - mysql

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    links:
      - "mysql"
    environment:
      DB_HOST: "mysql"
      DB_DATABASE: "kusum_clinic"
      DB_USER: "root"
      DB_PASSWORD: "DL9ca#)$!"
      DB_PORT: 3307
      SERVER_PORT: 8080
      NODE_ENV: "production"
    depends_on:
      - scripts
      - mysql

  scripts:
    build:
      context: ./scripts
    environment:
      DB_HOST: "mysql"
      DB_NAME: "kusum_clinic"
      DB_USER: "root"
      DB_PASSWORD: "DL9ca#)$!"
      DB_PORT: 3307
    links:
      - "mysql"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: DL9ca#)$!
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
