version: "3"
services:
  web:
    build:
      context: ./web
    environment:
      REACT_APP_SERVER_URL: "http://api:8080"
    ports:
      - "3000:3000"
    depends_on:
      - api
      - scripts
      - mysql

  api:
    build:
      context: ./api
    environment:
      SERVER_PORT: 8080
      NODE_ENV: "production"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "8080:8080"
    links:
      - ${DB_HOST}
    depends_on:
      - scripts
      - mysql

  scripts:
    build:
      context: ./scripts
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    links:
      - ${DB_HOST}
    depends_on:
      - ${DB_HOST}

  mysql:
    container_name: ${DB_HOST}
    image: mysql:latest
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
