version: "3"
services:
  web:
    build:
      context: ./web
    environment:
      REACT_APP_SERVER_URL: "http://localhost:8080"
    ports:
      - "3000:3000"
    depends_on:
      - api
      - scripts
      - mysql

  api:
    build:
      context: ./api
    environment:
      SERVER_PORT: 8080
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DOCWELL_REPORTS_STORAGE_CONNECTION_STRING: ${DOCWELL_REPORTS_STORAGE_CONNECTION_STRING}
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - scripts
      - mysql
    volumes:
      - data-dev:/app

  scripts:
    build:
      context: ./scripts
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_FIRST_USER: ${DB_FIRST_USER}
      DB_FIRST_PASSWORD: ${DB_FIRST_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - data-dev:/var/lib/mysql

volumes:
  data-dev:
