version: "3"
services:
  caddy:
    domainname: ${AZ_DOMAIN_NAME}
    image: ${AZ_REGISTRY_NAME}.azurecr.io/docwell_caddy:latest
    build:
      context: ./caddy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - AZ_DOMAIN_NAME=${AZ_DOMAIN_NAME}
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 0.2g

  web:
    domainname: ${AZ_DOMAIN_NAME}
    image: ${AZ_REGISTRY_NAME}.azurecr.io/docwell_web:latest
    build:
      context: ./web
    environment:
      REACT_APP_SERVER_URL: "https://${AZ_DOMAIN_NAME}.garvitkansal.com:8080"
    depends_on:
      - api
      - scripts
      - mysql
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "1.5"
          memory: 1.5g

  api:
    domainname: ${AZ_DOMAIN_NAME}
    image: ${AZ_REGISTRY_NAME}.azurecr.io/docwell_api:latest
    build:
      context: ./api
    environment:
      SERVER_PORT: 8079
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DOCWELL_REPORTS_STORAGE_CONNECTION_STRING: ${AZ_STORAGE_ACCOUNT_CONNECTION_STRING}
    depends_on:
      - scripts
      - mysql
    volumes:
      - data-prod:/app
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 0.5g

  scripts:
    image: ${AZ_REGISTRY_NAME}.azurecr.io/docwell_scripts:latest
    build:
      context: ./scripts
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_FIRST_USER: ${DB_FIRST_USER}
      DB_FIRST_PASSWORD: ${DB_FIRST_PASSWORD}
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 0.5g

  mysql:
    image: mysql:latest
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data-prod:/var/lib/mysql
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 0.5g

volumes:
  data-prod:
    driver: azure_file
    driver_opts:
      share_name: ${AZ_STORAGE_ACCOUNT_SHARE}
      storage_account_name: ${AZ_STORAGE_ACCOUNT_NAME}
