version: "3"
services:
  web:
    image: ${AZ_REGISTRY_NAME}.azurecr.io/docwell_web:latest
    domainname: docwell
    build:
      context: ./web
    environment:
      REACT_APP_SERVER_URL: "http://api:8080"
    ports:
      - "3000:3000"
    depends_on:
      - api
      - scripts
      - mysql
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "1.5"
          memory: 1600M

  api:
    image: ${AZ_REGISTRY_NAME}.azurecr.io/docwell_api:latest
    build:
      context: ./api
    environment:
      SERVER_PORT: 8080
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DOCWELL_REPORTS_STORAGE_CONNECTION_STRING: ${DOCWELL_REPORTS_STORAGE_CONNECTION_STRING}
    ports:
      - "8080:8080"
    depends_on:
      - scripts
      - mysql
    volumes:
      - api-data-prod:/app
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  scripts:
    image: ${AZ_REGISTRY_NAME}.azurecr.io/docwell_scripts:latest
    build:
      context: ./scripts
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_FIRST_USER: ${DB_FIRST_USER}
      DB_FIRST_PASSWORD: ${DB_FIRST_PASSWORD}
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  mysql:
    image: mysql:latest
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - mysql-data-prod:/var/lib/mysql
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

volumes:
  api-data-prod:
    driver: azure_file
    driver_opts:
      share_name: myapidata
      storage_account_name: ${AZ_STORAGE_ACCOUNT_NAME}
  mysql-data-prod:
    driver: azure_file
    driver_opts:
      share_name: mysqldata
      storage_account_name: ${AZ_STORAGE_ACCOUNT_NAME}
