version: "3"
services:
  web:
    domainname: ${DOMAIN_NAME}
    container_name: web
    build:
      context: ./web
    environment:
      REACT_APP_SERVER_URL: "http://localhost:${SERVER_PORT}"
    ports:
      - "3000:3000"
    depends_on:
      - api
      - scripts
      - mysql

  api:
    container_name: api
    build:
      context: ./api
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: ${SERVER_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DOCWELL_REPORTS_STORAGE_CONNECTION_STRING: ${DOCWELL_REPORTS_STORAGE_CONNECTION_STRING}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    links:
      - ${DB_HOST}
    depends_on:
      - scripts
      - mysql
    volumes:
      - ${API_VOLUME}:/app

  scripts:
    container_name: scripts
    build:
      context: ./scripts
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_FIRST_USER: ${DB_FIRST_USER}
      DB_FIRST_PASSWORD: ${DB_FIRST_PASSWORD}
    links:
      - ${DB_HOST}
    depends_on:
      - ${DB_HOST}

  mysql:
    container_name: mysql
    image: docwell.azurecr.io/mysql:latest
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql

volumes:
  api-data-prod:
  mysql-data-prod:
