name: BuildDeploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Log in to Azure Container Registry
        run: |
          curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
          # docker login azure --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}
          docker login -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} ${{ secrets.ACR_USERNAME }}.azurecr.io
          docker context create aci docwellcontext --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --subscription-id ${{ secrets.AZURE_SUB_ID }}
          docker context use docwellcontext

      - name: Setup .env file
        run: |
          touch .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_USER=${{ vars.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_FIRST_USER=${{ vars.DB_FIRST_USER }}" >> .env
          echo "DB_FIRST_PASSWORD=${{ secrets.DB_FIRST_PASSWORD }}" >> .env
          echo "DB_VOLUME=${{ vars.DB_VOLUME }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
          echo "SERVER_ENV=${{ vars.SERVER_ENV }}" >> .env
          echo "SERVER_PORT=${{ vars.SERVER_PORT }}" >> .env
          echo "ASA_NAME=${{ vars.ASA_NAME }}" >> .env
          echo "ASA_DB_FILESHARE=${{ vars.ASA_DB_FILESHARE }}" >> .env
          echo "DOMAIN_NAME=${{ vars.DOMAIN_NAME }}" >> .env
          echo "DOCWELL_REPORTS_STORAGE_CONNECTION_STRING=${{ secrets.DOCWELL_REPORTS_STORAGE_CONNECTION_STRING }}" >> .env

      - name: Build Docker Images
        run: |
          docker-compose --env-file .env build

      - name: Push Docker Images
        run: |
          docker-compose --env-file .env up
