name: BuildDeploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Build and push Docker images
        run: |
          chmod +x main.github.sh
          ./main.github.sh
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_FIRST_USER: ${{ env.DB_FIRST_USER }}
          DB_FIRST_PASSWORD: ${{ secrets.DB_FIRST_PASSWORD }}
          DB_VOLUME: ${{ env.DB_VOLUME }}
          DB_PORT: ${{ env.DB_PORT }}
          SERVER_ENV: ${{ env.SERVER_ENV }}
          API_VOLUME: ${{ env.API_VOLUME }}
          SERVER_PORT: ${{ env.SERVER_PORT }}
          ACR_USERNAME: ${{ env.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          DOCWELL_REPORTS_STORAGE_CONNECTION_STRING: ${{ secrets.DOCWELL_REPORTS_STORAGE_CONNECTION_STRING }}
