name: BuildDeploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Build and push Docker images
        run: |
          chmod +x main.github.sh
          touch .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_USER=${{ vars.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_FIRST_USER=${{ vars.DB_FIRST_USER }}" >> .env
          echo "DB_FIRST_PASSWORD=${{ secrets.DB_FIRST_PASSWORD }}" >> .env
          echo "DB_VOLUME=${{ vars.DB_VOLUME }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
          echo "SERVER_ENV=${{ vars.SERVER_ENV }}" >> .env
          echo "API_VOLUME=${{ vars.API_VOLUME }}" >> .env
          echo "SERVER_PORT=${{ vars.SERVER_PORT }}" >> .env
          echo "ACR_USERNAME=${{ vars.ACR_USERNAME }}" >> .env
          echo "ACR_PASSWORD=${{ secrets.ACR_PASSWORD }}" >> .env
          echo "DOCWELL_REPORTS_STORAGE_CONNECTION_STRING=${{ secrets.DOCWELL_REPORTS_STORAGE_CONNECTION_STRING }}" >> .env
          cat .env
          ./main.github.sh
