name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    environment: !PUT_ENV_HERE
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          touch .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "AZ_STORAGE_ACCOUNT_CONNECTION_STRING=${{ secrets.AZ_STORAGE_ACCOUNT_CONNECTION_STRING }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_FIRST_USER=${{ vars.DB_FIRST_USER }}" >> .env
          echo "DB_FIRST_PASSWORD=${{ secrets.DB_FIRST_PASSWORD }}" >> .env
          echo "AZ_STORAGE_ACCOUNT_NAME=${{ vars.AZ_STORAGE_ACCOUNT_NAME }}" >> .env
          echo "AZ_REGISTRY_NAME=${{ vars.AZ_REGISTRY_NAME }}" >> .env
          echo "AZ_STORAGE_ACCOUNT_SHARE=${{ vars.AZ_STORAGE_ACCOUNT_SHARE }}" >> .env

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_SECURITY_CREDS }}

      - name: Install Docker Compose CLI
        run: >
          curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

      - name: Docker Login to Azure
        run: |
          CLIENT_ID=$(echo '${{ secrets.AZ_SECURITY_CREDS }}' | jq --raw-output .clientId)
          CLIENT_SECRET=$(echo '${{ secrets.AZ_SECURITY_CREDS }}' | jq --raw-output .clientSecret)
          TENANT_ID=$(az account show --query homeTenantId --output tsv)
          docker login azure --client-id "$CLIENT_ID" --client-secret "$CLIENT_SECRET" --tenant-id "$TENANT_ID"
          az acr login --name "${{ vars.AZ_REGISTRY_NAME }}" --username "$CLIENT_ID" --password "$CLIENT_SECRET"

      - name: Create ACI context
        run: |
          docker context create aci acictx --resource-group "${{ vars.AZ_RESOURCE_GROUP }}" --location "${{ vars.AZ_LOCATION }}" --subscription-id "${{ secrets.AZ_SUBSCRIPTION_ID }}"
          docker context use acictx

      - name: Deploy the app
        run: |
          docker-compose -f "$GITHUB_WORKSPACE/docker-compose.aci.yml" --env-file .env --verbose config
          export $(cat .env | xargs) && docker compose -f "$GITHUB_WORKSPACE/docker-compose.aci.yml" --verbose up
